### ISSUE TITLE
Problem about update.

### ISSUE THREAD

**Issue by yearmfew** [MethodJules/concept_map_tool#9]
In page daily scrum, I am updating the data. It changes the data in Database and State.
I am taking the data by getter and it brings the new changed data to the page. 
I am trying to detect the change with watch.
But somehow Vue does not detect the change in getter and does not changes the data in html dom. 
When I reload the page I can see my changes but without reload I cannot see the changes. 

You can see this bug under develop and develop_daily branch.

**Comment by StephanMende** [comment]
@yearmfew Vue v2.x cannot detect changes to an array if you update it using an index. https://vuejs.org/v2/guide/reactivity.html#For-Arrays describes this problem.

E. g. replacing `state.rowData[index] = dailyEntry;` with `state.rowData.splice(index, 1, dailyEntry);` in [dailyScrum.js](https://github.com/MethodJules/concept_map_tool/blob/d6df8a683f52a4ba6389a8242e6e49fd2de3ac95/src/store/modules/dailyScrum.js#L125) will work.

**Comment by yearmfew** [comment]
Thank you @StephanMende. It works now. I have read this but I could not understand how to solve. 
Thank you very much again.
